In [8]:
import tensorflow as tf
import math

In [9]:
x = tf.constant([-float("inf"), -9, -0.5, 1, 1.2, 200, 10000, float("inf")])
tf.math.cos(x) # ==> [nan -0.91113025 0.87758255 0.5403023 0.36235774 0.48718765 -0.95215535 nan]

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([        nan, -0.91113025,  0.87758255,  0.5403023 ,  0.36235774,
        0.48718765, -0.95215535,         nan], dtype=float32)>

convert_to_tensor(...): Converts the given value to a Tensor.

This function converts Python objects of various types to Tensor objects. It accepts Tensor objects, numpy arrays, Python lists, and Python scalars.

https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor


In [10]:
#Testes das funções trigonométricas pelo tensorflow
y = tf.constant([math.pi/6,math.pi/3])
tf.math.sin(y)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5       , 0.86602545], dtype=float32)>

In [4]:
import numpy as np

def my_func(arg):
  arg = tf.convert_to_tensor(arg, dtype=tf.float32)
  return arg

In [5]:
value_1 = my_func(tf.constant(x))
print(value_1)

tf.Tensor([    -inf -9.0e+00 -5.0e-01  1.0e+00  1.2e+00  2.0e+02  1.0e+04      inf], shape=(8,), dtype=float32)


In [6]:
type(value_1)

tensorflow.python.framework.ops.EagerTensor