In [2]:
import tensorflow as tf
import math

2021-08-03 20:42:23.878853: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-03 20:42:23.878879: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [8]:
x = tf.constant([-float("inf"), -9, -0.5, 1, 1.2, 200, 10000, float("inf")])
teste = tf.math.cos(x) # ==> [nan -0.91113025 0.87758255 0.5403023 0.36235774 0.48718765 -0.95215535 nan]

In [9]:
print(teste)

tf.Tensor(
[        nan -0.91113025  0.87758255  0.5403023   0.36235774  0.48718765
 -0.95215535         nan], shape=(8,), dtype=float32)


convert_to_tensor(...): Converts the given value to a Tensor.

This function converts Python objects of various types to Tensor objects. It accepts Tensor objects, numpy arrays, Python lists, and Python scalars.

https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor


In [4]:
#Testes das funções trigonométricas pelo tensorflow
y = tf.constant([math.pi/6,math.pi/3])
tf.math.sin(y)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5       , 0.86602545], dtype=float32)>

In [5]:
import numpy as np

def my_func(arg):
  arg = tf.convert_to_tensor(arg, dtype=tf.float32)
  return arg

In [6]:
value_1 = my_func(tf.constant(teste))
print(value_1)

tf.Tensor(
[        nan -0.91113025  0.87758255  0.5403023   0.36235774  0.48718765
 -0.95215535         nan], shape=(8,), dtype=float32)


In [10]:
type(value_1)

tensorflow.python.framework.ops.EagerTensor

In [11]:
value_2 = my_func(tf.constant(x))
print(value_2)

tf.Tensor([    -inf -9.0e+00 -5.0e-01  1.0e+00  1.2e+00  2.0e+02  1.0e+04      inf], shape=(8,), dtype=float32)
